"""empty message

Revision ID: 51f8f8c6061a
Revises: ea05d4a1b94e
Create Date: 2021-08-04 12:06:20.483648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f8f8c6061a'
down_revision = 'ea05d4a1b94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('patientCardId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientCardId'], ['patientCards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doctors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='doctors_pkey'),
    sa.UniqueConstraint('email', name='doctors_email_key')
    )
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
