"""empty message

Revision ID: ea05d4a1b94e
Revises: da69e12e4ad5
Create Date: 2021-08-04 11:50:37.675654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea05d4a1b94e'
down_revision = 'da69e12e4ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'doctor')
    # ### end Alembic commands ###
